spring:
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      enabled: false
      max-file-size: 10MB
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mariadb://localhost:3306/delivery?createDatabaseIfNotExist=true&useSSL=false&autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&failOverReadOnly=false&allowMultiQueries=true&serverTimezone=Africa/Harare
    username: 'user'
    password: 'password'
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useLocalSessionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false
      maximum-pool-size: 10

  jpa:
    database-platform: org.hibernate.dialect.MariaDB106Dialect
    database: MYSQL
    hibernate:
      ddl-auto: update

    properties:
      hypersistence:
        query:
          max_result_size: 50
        session:
          flush_timeout_millis: 100
          timeout_millis: 250

      hibernate.format_sql: false
      hibernate.use_sql_comments: false
      hibernate.id.new_generator_mappings: true
      hibernate.connection.provider_disables_autocommit: true
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false
      hibernate.jdbc.batch_size: 500
      hibernate.order_inserts: true
      hibernate.order_updates: true
      hibernate.query.fail_on_pagination_over_collection_fetch: true
      hibernate.query.in_clause_parameter_padding: true
      hibernate.query.plan_cache_max_size: 8192
    open-in-view: false
    defer-datasource-initialization: true
  data:
    jpa:
      repositories:
        bootstrap-mode: lazy

  jackson:
    serialization:
      fail-on-empty-beans: false

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

server:
  servlet:
    context-path: /api/v1

logging:
  level:
    org.springframework.web: INFO
    org.hibernate: ERROR

app:
  security:
    jwtSecret: JWTSuperSecretKey
    jwtExpirationInMs: 604800000

---

spring:
  config:
    activate:
      on-profile: test
      h2:
        console:
          enabled: true

logging:
  level:
    org.springframework.web: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: '*'
